version: '3.7'
services:
  postgres:
    container_name: 'todo-postgres'
    image: 'postgres'
    restart: 'always'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=todo'
      - 'POSTGRES_PASSWORD=postgres'
